# Generated by Django 2.2.7 on 2019-11-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0002_auto_20191126_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cardNo',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
