# Generated by Django 2.2.7 on 2019-11-26 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0003_auto_20191126_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overheadreq',
            name='mealType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.Meal'),
        ),
        migrations.AlterField(
            model_name='overheadreq',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.Student'),
        ),
        migrations.AlterField(
            model_name='rebatereq',
            name='fromDate',
            field=models.DateField(help_text='format : DDMMYYYY', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rebatereq',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.Student'),
        ),
        migrations.AlterField(
            model_name='rebatereq',
            name='toDate',
            field=models.DateField(help_text='format : DDMMYYYY', max_length=10, null=True),
        ),
    ]
