# Generated by Django 2.2.7 on 2019-11-27 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0004_auto_20191126_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overheadreq',
            name='mealType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.Meal'),
        ),
        migrations.AlterField(
            model_name='overheadreq',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermgmt.Student'),
        ),
    ]
